spring:
  application:
    name: demo
  profiles:
    active: dev
  #多国语文件路径及编码配置
  messages:
    basename: i18n/messages
    encoding: UTF-8

# Mybatis configuration
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: top.model
  identity: MYSQL
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #sql语句日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
