server:
  port: 9000

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  #    cluster-nodes: 81.68.206.246:9300
  #    cluster-name: my-application
  elasticsearch:
    rest:
      uris: ["http://81.68.206.246:9200"]






